server:
  port: 8089

spring:
  application:
    name: mobile-level
  datasource:
    driverClassName: org.apache.phoenix.jdbc.PhoenixDriver
    # zookeeper 地址
    url: jdbc:phoenix:124.223.103.8:2181
    username:
    password:
    # spring-boot 2.X 默认采用高性能的 Hikari 作为连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为。默认为 true
      auto-commit: true
      # 允许最长空闲时间
      idle-timeout: 30000
      # 此属性表示连接池的用户定义名称，主要显示在日志记录和 JMX 管理控制台中，以标识池和池配置。 默认值：自动生成
      pool-name: custom-hikari
      #此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30 分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认 30 秒，即 30000
      connection-timeout: 30000
      # 连接测试 sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
      connection-test-query: SELECT 1



mybatis:
  mapper-locations: classpath:mappers/*.xml




logging:
  level:
    root: info
  pattern:
  #    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
    file-name-pattern: ${spring.application.name}.%d{yyyy-MM-dd}.%i.log
    max-file-size: 10MB