
spring:
  application:
    name: mobile-level
  profiles:
    active: pro
    group:
      "dev": dev
      "pro": pro



mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




logging:
  level:
    root: info
  pattern:
  #    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
    file-name-pattern: ${spring.application.name}.%d{yyyy-MM-dd}.%i.log
    max-file-size: 10MB