server:
  port: 8088
spring:
  application:
    admin:
      enabled: true
  boot:
    admin:
    client:
    url: http://localhost:8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
